### ISSUE TITLE
Using c++

### ISSUE THREAD

**Issue by shersoni610** [lakeraai/onnx_clip#2]
Hi, since the onnx is supported in opencv and c++, I was wondering if there is an example using it.

Thanks

**Comment by vvolhejn** [comment]
Hi! I'm afraid we don't support C++ officially. To get CLIP running in C++, the simplest way would be to download the .onnx models for both text and vision from our S3 bucket, see [here](https://github.com/lakeraai/onnx_clip/blob/d28d230e498a37536f3c8e408911d8a3020595f0/onnx_clip/model.py#L186). Then you'd have to re-implement the [preprocessing](https://github.com/lakeraai/onnx_clip/blob/main/onnx_clip/preprocessor.py), which takes place outside of ONNX. Good luck!
